version: "3"

networks:
  nginx-network:
#     external: false

services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl.conf:/etc/nginx/sslpref.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - ./nginx/letsencrypt/:/etc/letsencrypt/
      - ./nginx/www/:/data/letsencrypt/
    networks: 
      - nginx-network 
    ports:
      - "80:80"
      - "443:443"
  
  zoom-coordinator:
    container_name: zoom-coordinator
    build: ./zoom-coordinator
    restart: always 
    networks: 
      - nginx-network 
    ports:
      - "80"
    volumes:
      - ./zoom-coordinator/index.db:/usr/src/app/index.db

  mariadb:
    container_name: mariadb
    image: mariadb:10.4
    restart: always
    volumes:
      - ./mariadb/db/:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: czc
      MYSQL_ROOT_PASSWORD: zoom
      MYSQL_USER: zoom
      MYSQL_PASSWORD: zoom
    networks: 
      - nginx-network 
